### ISSUE TITLE
@vue/eslint-config-typescript@13.0.0依赖eslint8，和项目依赖的eslint9有冲突

### ISSUE THREAD

**Issue by sumile-ting** [syh-micro-build/mb-admin#2]
问题描述：
最新代码npm install后报错，采用npm install --force安装后，提交代码报错，提示eslint9默认的配置文件是eslint.config.js。
因为@vue/eslint-config-typescript@13.0.0依赖eslint8，和package.json中的eslint9冲突。

建议：
采用eslint8

**Comment by ShanYi-Hui** [comment]
降级是不可能降级的，已经修复，大版本已更至最新，冲突都处理了
